CREATE DATABASE MDB;
USE MDB;
CREATE TABLE TYPE_TABLE(
TYPEID INT PRIMARY KEY AUTO_INCREMENT,
TYPENAME VARCHAR(50)
);

CREATE TABLE SP_TABLE(
SPID INT PRIMARY KEY AUTO_INCREMENT,
TYPEID INT,
SPNAME VARCHAR(40),
FOREIGN KEY (TYPEID) REFERENCES TYPE_TABLE(TYPEID)
);


INSERT INTO TYPE_TABLE VALUES(101,'水果'),(102,'蔬菜'),(103,'肉类');
INSERT into SP_TABLE VALUES(1,101,'苹果'),(2,102,'辣椒'),(3,103,'小龙虾');
